service: my-serverless-kanban-app

provider:
  name: aws
  runtime: python3.8
  region: us-east-2 
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-table
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    CardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: backend.app.app  

  pythonRequirements:
    dockerizePip: true
