export const NEW_WORK_ITEM_ITEM = "MK_NEW_WORK_ITEM_ITEM";
export const UPDATE_WORK_ITEM_ITEM = "MK_UPDATE_WORK_ITEM_ITEM";
export const UPDATE_WORK_ITEMS = "MK_UPDATE_WORK_ITEMS";
export const REMOVE_WORK_ITEM = "MK_REMOVE_WORK_ITEM";
export const ADD_STAGE = "ADD_STAGE";
export const REMOVE_STAGE = "REMOVE_STAGE";
export const INIT_STATE = "INIT_STATE";